### ISSUE TITLE
use of undeclared identifier 'ZMQ_BLOCKY'     setContextSetting(

### ISSUE THREAD

**Issue by Scarzer** [jship/CpperoMQ#1]
While trying to build the project against libzmq version 4.1.3, I came across this issue. 

ZMQ_BLOCKY is introduced in 4.2.x (http://api.zeromq.org/4-2:zmq-ctx-set)

Minor issue I guess, but the README suggests that all 4.x versions are supported

**Comment by jship** [comment]
Addressed in the v0.0.2 release.  Thanks!
