### ISSUE TITLE
How to create pollItem?

### ISSUE THREAD

**Issue by buma** [jship/CpperoMQ#2]
Hello!

This seems a great library for ZMQ, but I have a problem creating PollItem. Since all the constructors [are private](https://github.com/jship/CpperoMQ/blob/master/include/CpperoMQ/PollItem.hpp#L59). Public constructors are only for copying.

**Comment by jship** [comment]
To create a PollItem, you'll want to use the `isReceiveReady`, `isSendReady`, or `isSendOrReceiveReady` functions from `CpperoMQ/PollItem.hpp`.  These functions are passed the socket and a `PollItem::Callback` (synonym for a void function taking no args) and will then construct the correct `PollItem` for you.  You can then pass as many `PollItem` instances as you'd like to a `Poller`'s `poll` method and it will take care of the details of calling each one's callback when send/receive is ready on the socket.

Take a look at the companion repo, [CpperoMQ-examples](https://github.com/jship/CpperoMQ-examples)'s [rrbroker.cpp](https://github.com/jship/CpperoMQ-examples/blob/d21031ad5bfd6874d941b14364320822574ccd91/zguide/rrbroker.cpp) and [mspoller.cpp](https://github.com/jship/CpperoMQ-examples/blob/d21031ad5bfd6874d941b14364320822574ccd91/zguide/mspoller.cpp) for some concrete examples.  For the callbacks, those examples use C++11 lambdas with captures to get access to data in the enclosing scope.  That repo has more examples from the zguide and some extra CpperoMQ-specific examples.

Thanks for your interest in the library!

**Comment by buma** [comment]
Thanks, examples will help. It makes more sense know.

It seems I missed link to them in a Readme.

Do you have any idea why did I need to add `inline` to Poller functions (constructor and get/set Timeout) to get it to compile? Otherwise I got multiple definition linker errors.

I use g++ (GCC) 5.2.0 and 

```
clang version 3.7.0 (tags/RELEASE_370/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

**Comment by jship** [comment]
Nice find!  Added the missing inlines to the `Poller` functions and created a v0.0.3 release.  Let me know if that works correctly now for you.

**Comment by buma** [comment]
Thanks. It works correctly now.
