### ISSUE TITLE
Documentation is incomplete/unavailable

### ISSUE THREAD

**Issue by sunkin351** [jship/CpperoMQ#5]
Functions and classes such as your socket Poller are undocumented, and using the original zmq_poller is not possible because of incompatible variable types.

Undocumented:
Your Poller
Your Proxy
How to define a socket connection type (ex. whether it is tcp or udp, and what the address is...)

(for that matter, I don't see any official documentation at all, can you pls add some?)

**Comment by jship** [comment]
Thanks for you interest in the library.

I've intentionally kept the library's source free of comments and have instead provided the companion [CpperoMQ-examples](https://github.com/jship/CpperoMQ-examples) repo.  This repo runs through a sampling of CpperoMQ implementations of the examples provided in ZeroMQ's official [zguide](http://zguide.zeromq.org/page:all).  This repo also contains extra examples not covered in zguide that are useful for users of CpperoMQ.

Examples of working with the specific items you've mentioned are in the following source files:
1. Poller -> [zguide/mspoller.cpp](https://github.com/jship/CpperoMQ-examples/blob/d21031ad5bfd6874d941b14364320822574ccd91/zguide/mspoller.cpp), [zguide/rrbroker.cpp](https://github.com/jship/CpperoMQ-examples/blob/d21031ad5bfd6874d941b14364320822574ccd91/zguide/rrbroker.cpp)
2. Proxy -> [zguide/msgqueue.cpp](https://github.com/jship/CpperoMQ-examples/blob/d21031ad5bfd6874d941b14364320822574ccd91/zguide/msgqueue.cpp), [extra/pubsubqueue.cpp](https://github.com/jship/CpperoMQ-examples/blob/d21031ad5bfd6874d941b14364320822574ccd91/extra/pubsubqueue.cpp)
3. Defining socket connections (TCP, address, etc.) -> viewing the examples repo should clear up confusion on this too.  It is done the same way as using ZeroMQ directly.

Note that a `CpperoMQ::Socket` can be explicitly cast to `void*` when ZeroMQ needs to be used directly.

**Comment by sunkin351** [comment]
Thanks, for everyone's convenience, could you post the examples repo somewhere readily available to those visiting the front page of this repo?

**Comment by jship** [comment]
I have added a link to the [CpperoMQ-examples](https://github.com/jship/CpperoMQ-examples) repo earlier in the README with commit ced9ba66dfe48a12dde10aaadfa1f1da6cee99e2.  I also added a link to it as CpperoMQ's homepage in the top one-liner description of the repo.

Thanks!  I'll close out this issue.

**Comment by sunkin351** [comment]
Your welcome.
